name: igw-ci-cd
on: [push]
jobs:
  deploy_dev:
    name: deploy_dev
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./index.html,./bootstrap.css,./bootstrap.js,./error.html,./gallerystyle.css"
        target: "/var/www/html/"
  deploy_prod:
    name: deploy_prod
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "."
        target: "/var/www/html/"
